(()=>{
  const storeKey='primeboostly.admin.content.v1';
  const read=()=>{try{return JSON.parse(localStorage.getItem(storeKey)||'{}')}catch{return {}}};
  const write=v=>localStorage.setItem(storeKey,JSON.stringify(v));
  const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const toast=(message)=>{let el=document.querySelector('.admin-action-toast');if(!el){el=document.createElement('div');el.className='admin-action-toast';el.setAttribute('role','status');document.body.appendChild(el)}el.textContent=message;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2200)};
  const dialog=document.createElement('dialog');dialog.className='admin-editor-dialog';document.body.appendChild(dialog);
  const openEditor=trigger=>{
    const key=trigger.dataset.editorKey,kind=trigger.dataset.editorKind||'content',saved=read()[key]||{},title=saved.title||trigger.dataset.editorTitle||'Content',subject=saved.subject||trigger.dataset.editorSubject||'',status=saved.status||(kind==='email'?'Active':'Published'),content=saved.content||'';
    dialog.innerHTML=`<div class="admin-editor-head"><div><h2>Edit ${esc(title)}</h2><p>${kind==='email'?'Update the email template shown to customers.':'Update this customer-facing homepage section.'}</p></div><button class="admin-editor-close" type="button" aria-label="Close">×</button></div><form class="admin-editor-form"><label class="admin-editor-field">Title<input name="title" value="${esc(title)}" required></label>${kind==='email'?`<label class="admin-editor-field">Subject<input name="subject" value="${esc(subject)}" required></label>`:''}<label class="admin-editor-field">Status<select name="status">${(kind==='email'?['Active','Disabled']:['Published','Draft']).map(v=>`<option${v===status?' selected':''}>${v}</option>`).join('')}</select></label><label class="admin-editor-field">Content<textarea name="content" placeholder="Enter content for this ${kind==='email'?'email template':'homepage section'}">${esc(content)}</textarea></label><div class="admin-editor-actions"><button class="admin-editor-cancel" type="button">Cancel</button><button class="admin-editor-save" type="submit">Save Changes</button></div></form>`;
    dialog.querySelector('.admin-editor-close').onclick=()=>dialog.close();dialog.querySelector('.admin-editor-cancel').onclick=()=>dialog.close();
    dialog.querySelector('form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),data={title:String(fd.get('title')||'').trim(),subject:String(fd.get('subject')||'').trim(),status:String(fd.get('status')||''),content:String(fd.get('content')||'')};const all=read();all[key]=data;write(all);document.querySelectorAll(`[data-editor-key="${CSS.escape(key)}"]`).forEach(node=>{node.dataset.editorTitle=data.title;if(data.subject)node.dataset.editorSubject=data.subject;const row=node.closest('[data-content-row]')||node;if(row.querySelector('[data-content-title]'))row.querySelector('[data-content-title]').textContent=data.title;if(row.querySelector('[data-content-subject]'))row.querySelector('[data-content-subject]').textContent=data.subject;const badge=row.querySelector('[data-content-status]');if(badge){badge.textContent=data.status;badge.classList.toggle('neutral',data.status==='Draft'||data.status==='Disabled')}const updated=row.querySelector('[data-content-updated]');if(updated)updated.textContent='Just now'});dialog.close();toast(`${data.title} saved in this preview.`)};
    dialog.showModal();setTimeout(()=>dialog.querySelector('input')?.focus(),0);
  };
  document.querySelectorAll('[data-edit-content]').forEach(el=>{el.addEventListener('click',()=>openEditor(el));el.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&el.getAttribute('role')==='button'){e.preventDefault();openEditor(el)}})});

  const logoInputs=[...document.querySelectorAll('[data-logo-input]')];
  document.querySelectorAll('[data-logo-upload]').forEach((button,index)=>button.addEventListener('click',()=>logoInputs[index]?.click()));
  logoInputs.forEach(input=>input.addEventListener('change',()=>{const file=input.files?.[0];if(!file)return;if(file.size>5*1024*1024){toast('Logo must be 5 MB or smaller.');input.value='';return}const reader=new FileReader();reader.onload=()=>{document.querySelectorAll('.at-logo-preview,.atm-logo-preview').forEach(preview=>{preview.innerHTML=`<img src="${reader.result}" alt="PrimeBoostly logo preview">`});try{localStorage.setItem('primeboostly.admin.logo.preview',String(reader.result))}catch{}toast('Logo preview updated in this browser.')};reader.readAsDataURL(file)}));
  const savedLogo=localStorage.getItem('primeboostly.admin.logo.preview');if(savedLogo)document.querySelectorAll('.at-logo-preview,.atm-logo-preview').forEach(preview=>{preview.innerHTML=`<img src="${savedLogo}" alt="PrimeBoostly logo preview">`});

  const emailDefaults={driver:'SMTP',host:'smtp.example.com',port:'587',encryption:'TLS',fromName:'Prime Boostly',fromEmail:'support@primeboostly.com',testRecipient:'user@example.com'};
  let savedEmail={};try{savedEmail=JSON.parse(localStorage.getItem('primeboostly.admin.email-settings')||'{}')}catch{}
  document.querySelectorAll('[data-email-setting]').forEach(field=>{const key=field.dataset.emailSetting;if(savedEmail[key]!==undefined)field.value=savedEmail[key];const sync=()=>document.querySelectorAll(`[data-email-setting="${CSS.escape(key)}"]`).forEach(peer=>{if(peer!==field)peer.value=field.value});field.addEventListener('input',sync);field.addEventListener('change',sync)});
  const collectEmailSettings=()=>{const out={...emailDefaults};document.querySelectorAll('[data-email-setting]').forEach(field=>{out[field.dataset.emailSetting]=field.value.trim()});return out};
  document.querySelectorAll('[data-email-settings-save]').forEach(button=>button.addEventListener('click',()=>{const data=collectEmailSettings();localStorage.setItem('primeboostly.admin.email-settings',JSON.stringify(data));document.querySelectorAll('[data-email-setting]').forEach(field=>{const key=field.dataset.emailSetting;if(data[key]!==undefined)field.value=data[key]});toast('SMTP settings saved in this preview.')}));
  document.querySelectorAll('[data-email-test]').forEach(button=>button.addEventListener('click',()=>{const data=collectEmailSettings(),target=data.testRecipient||'user@example.com';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(target)){toast('Enter a valid test recipient email.');return}toast(`Preview test email prepared for ${target}. No production email was sent.`)}));

  const saved=read();document.querySelectorAll('[data-editor-key]').forEach(node=>{const data=saved[node.dataset.editorKey];if(!data)return;node.dataset.editorTitle=data.title||node.dataset.editorTitle;if(data.subject)node.dataset.editorSubject=data.subject;const row=node.closest('[data-content-row]')||node;if(row.querySelector('[data-content-title]')&&data.title)row.querySelector('[data-content-title]').textContent=data.title;if(row.querySelector('[data-content-subject]')&&data.subject)row.querySelector('[data-content-subject]').textContent=data.subject;const badge=row.querySelector('[data-content-status]');if(badge&&data.status){badge.textContent=data.status;badge.classList.toggle('neutral',data.status==='Draft'||data.status==='Disabled')}});
})();
