(()=>{
  const feedback=document.querySelector('[data-cd-feedback]');
  const toast=message=>{if(!feedback)return;feedback.textContent=message;feedback.classList.add('show');clearTimeout(feedback._t);feedback._t=setTimeout(()=>feedback.classList.remove('show'),1800)};
  const copy=async value=>{try{await navigator.clipboard.writeText(value);toast('Copied to clipboard.')}catch{toast('Copy is unavailable in this preview browser.')}};
  document.querySelectorAll('[data-copy-endpoint]').forEach(b=>b.addEventListener('click',()=>copy(document.querySelector('[data-api-endpoint]')?.value||'https://primeboostly.com/api/v2')));
  document.querySelectorAll('[data-copy-key]').forEach(b=>b.addEventListener('click',()=>copy('pb_live_preview_key')));
  let keyVersion=1;document.querySelectorAll('[data-regenerate-key]').forEach(b=>b.addEventListener('click',()=>{keyVersion++;document.querySelectorAll('[data-api-key]').forEach(x=>x.textContent=`pb_live_preview_${String(keyVersion).padStart(2,'0')}_••••••••`);toast('Preview API key regenerated.')}));
  document.querySelectorAll('[data-ticket-create]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form).entries());if(!String(data.subject||'').trim()||!String(data.message||'').trim()){toast('Add a subject and message.');return}localStorage.setItem('primeboostly.preview.latest-ticket',JSON.stringify({...data,id:'T-220',createdAt:new Date().toISOString()}));toast('Ticket created in this preview.');setTimeout(()=>location.href='/ticket-detail.html',350)}));
  document.querySelectorAll('[data-ticket-reply]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const input=form.querySelector('[name="reply"]'),text=input?.value.trim();if(!text){toast('Write a reply first.');return}document.querySelectorAll('[data-ticket-thread]').forEach(thread=>{const msg=document.createElement('div');msg.className=thread.closest('.cd-mobile')?'cd-mobile-message me':'cd-message me';msg.innerHTML='<b>You · just now</b><p></p>';msg.querySelector('p').textContent=text;thread.appendChild(msg)});input.value='';document.querySelectorAll('[data-ticket-state]').forEach(x=>{x.textContent='Open';x.className='cd-pill'});toast('Reply added in this preview.')}));
  document.querySelectorAll('[data-ticket-close]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-ticket-state]').forEach(x=>{x.textContent='Closed';x.className='cd-pill neutral'});toast('Ticket closed in this preview.')}));
  document.querySelector('[data-ticket-attach]')?.addEventListener('click',()=>toast('Attachment picker is not connected in this static preview.'));
})();
