const {chromium}=require('playwright');
const assert=require('node:assert/strict'), http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{let file=path.join(root,new URL(req.url,'http://localhost').pathname);if(!path.extname(file))file+='.html';fs.readFile(file,(error,data)=>{if(error){res.writeHead(404);return res.end()}res.setHeader('Content-Type',file.endsWith('.css')?'text/css':file.endsWith('.js')?'application/javascript':file.endsWith('.svg')?'image/svg+xml':'text/html');res.end(data)})});
(async()=>{
 await new Promise(resolve=>server.listen(8085,resolve));
 const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--no-zygote','--single-process','--disable-gpu']}: {})});
 try{
 const context=await browser.newContext({viewport:{width:393,height:852}});
 await context.addInitScript(()=>sessionStorage.setItem('primeboostly.preview.session.v1',JSON.stringify({username:'QA',email:'qa@example.com'})));
 const page=await context.newPage(),base='http://localhost:8085',errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto(base+'/order-history');await page.getByRole('searchbox',{name:'Search order history'}).fill('1238');assert.equal(await page.locator('.history-mobile-card:visible').count(),1);
 await page.locator('.history-mobile-card:visible').click();await page.waitForURL('**/order-detail.html?*');assert.equal(await page.locator('[data-key=id] strong').innerText(),'1238');assert.equal(await page.locator('.odv2-processing').innerText(),'Partial');assert((await page.locator('[data-key=price] strong').innerText()).includes('4,900'));
 await page.goto(base+'/order-history');await page.getByRole('searchbox').fill('no matching history');assert(await page.getByText('No orders found',{exact:true}).isVisible());await page.getByRole('button',{name:'Clear search',exact:true}).click();assert.equal(await page.locator('.history-mobile-card:visible').count(),4);
 await page.goto(base+'/fund-history');assert.equal(await page.locator('.fund-mobile-status:visible').count(),3);
 await page.goto(base+'/support-flow?type=order');await page.getByRole('textbox',{name:'Order reference',exact:true}).fill('1238');await page.getByRole('textbox',{name:'Issue details',exact:true}).fill('Please review this order.');assert.equal(await page.getByRole('textbox',{name:'Issue details',exact:true}).evaluate(n=>n.tagName),'TEXTAREA');const submit=page.getByRole('link',{name:/Submit request/});assert.equal(await submit.getAttribute('aria-disabled'),'false');await submit.click();await page.waitForURL('**/support-flow.html?type=order&state=submitted');
 await page.goto(base+'/account-edit?type=email');await page.locator('[data-account-input]').fill('invalid-address');assert.equal(await page.locator('[data-account-submit]').getAttribute('aria-disabled'),'true');await page.locator('[data-account-input]').fill('new@example.com');assert.equal(await page.locator('[data-account-submit]').getAttribute('aria-disabled'),'false');
 await page.goto(base+'/new-ticket');await page.locator('.cd-mobile [name=subject]').fill('Please review order 1238');await page.locator('.cd-mobile [name=message]').fill('My order needs a status update.');await page.getByRole('button',{name:'Create Ticket',exact:true}).click();await page.waitForURL('**/ticket-detail.html');assert(await page.getByRole('heading',{name:'Ticket #T-220',exact:true}).isVisible());assert((await page.locator('.cd-mobile [data-ticket-thread]').innerText()).includes('My order needs a status update.'));await page.locator('.cd-mobile [name=reply]').fill('Here is another detail.');await page.getByRole('button',{name:'Send Reply',exact:true}).click();assert((await page.locator('.cd-mobile [data-ticket-thread]').innerText()).includes('Here is another detail.'));
 await page.goto(base+'/login');const password=page.locator('.auth-form-panel input[name=password]');await password.fill('PreviewPassword123!');await page.getByRole('button',{name:'Show enter password',exact:true}).click();assert.equal(await password.getAttribute('type'),'text');assert.equal(await password.inputValue(),'PreviewPassword123!');await page.getByRole('button',{name:'Hide enter password',exact:true}).click();assert.equal(await password.getAttribute('type'),'password');
 assert.deepEqual(errors,[]);console.log('PASS: history search/empty/reset/detail context, visible funding statuses, support multiline/review, account email validation, preview ticket create/reply and password visibility');
 }finally{await browser.close();server.close()}
})().catch(error=>{console.error(error);server.close();process.exitCode=1});
